version: "3"

services:
  shathel-docker-registry:
    image: registry:2.5
    ports:
      - 4000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    volumes:
      - shathel-docker-registry-data:/var/lib/registry
      - ./certs:/certs
    deploy:
      placement:
              constraints: [node.role == manager]
      resources:
        limits:
          memory: ${SHATHEL_ENV_REGISTRY_MEMORY_LIMIT:-2gb}              

volumes:
  shathel-docker-registry-data: