version: '3'
services:
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - 8082:8081
    volumes:
     - nexus-data:/nexus-data
    deploy:
      labels:
          com.df.notify: "true"
          com.df.distribute: "true"
          com.df.usersSecret: "monitoring"
          com.df.servicePath: "/nexus/"
          com.df.addReqHeader: "X-Forwarded-Proto https"
          com.df.denyHttp: "true"
          com.df.port: "8081"
    environment:
      - NEXUS_CONTEXT=nexus

volumes:
  nexus-data:
