version: '3'
services:
  artifactory:
    image: sonatype/nexus3:latest
    ports:
      - 8082:8081
    volumes:
     - nexus-data:/nexus-data
    deploy:
      labels:
          com.df.notify: "true"
          com.df.distribute: "true"
          com.df.usersSecret: "monitoring"
          com.df.servicePath: "/nexus/"
          com.df.reqPathReplace: /
          com.df.reqPathSearch: /nexus/
          com.df.port: "8081"

volumes:
  nexus-data: