version: '3'


services:
 standalone:
  image: minio/minio
  volumes:
   - data:/data
   - config:/root/.minio
  ports:
   - "9000:9000"
  networks:
    - minionet   
  environment:
   MINIO_ACCESS_KEY: ${SHATHEL_ENV_MINIO_ACCESS_KEY}
   MINIO_SECRET_KEY: ${SHATHEL_ENV_MINIO_SECRET_KEY}
  deploy:
   restart_policy:
    delay: 10s
    max_attempts: 10
    window: 60s
  command: server /data


volumes:
  data:
    labels:
      org.shathel.rexray: 'true'  
  config:
    labels:
      org.shathel.rexray: 'true'


networks:
  minionet:
