---
- hosts: all
  become: yes
  tasks:
        - name: Get public interface name
          shell: ip addr show | grep {{public_ip}} | cut -f2 | awk '{ print $7 }' | head
          register: pub_if_name_command
          changed_when: False
        - debug: msg={{pub_if_name_command}}
        - name: Get private name if public not avail (scaleway???)
          shell: ip addr show | grep {{private_ip}} | cut -f2 | awk '{ print $7 }' | head
          register: priv_if_name_command
          when: "pub_if_name_command.rc != 0 or pub_if_name_command.stdout == ''"
          changed_when: False
        - debug: msg={{priv_if_name_command}}
        - name: Save pub if name
          set_fact:
            public_if: "{{ pub_if_name_command.stdout }}"
          when: "pub_if_name_command.rc == 0 and pub_if_name_command.stdout != ''"
        - name: Save prv if name
          set_fact:
            public_if: "{{ priv_if_name_command.stdout }}"
          when: "pub_if_name_command.rc != 0 or pub_if_name_command.stdout == ''"
        - debug: msg={{public_if}}
          failed_when: public_if is not defined or public_if == ''
        - name: /etc/iptables dir present
          file:
            path: /etc/iptables
            state: directory


        - name: Shathel rules file (UDP)
          template:
              src: ./shathel.iptable.rules.j2
              dest: /etc/iptables/shathel.fwopener.{{ opener_stack_name }}.rules
              owner: root
              mode: 0644
          register: rules_command
          when: "opener_udp_ports != ''"
        - name: Adding shathel iptables rules applied on startup (UDP)
          template:
              src: ./shathel.iptable.apply.j2
              dest: /etc/network/if-pre-up.d/shathel-fwopener-{{ opener_stack_name }}-iptables
              owner: root
              mode: 0755
          when: "opener_udp_ports != ''"
        - name: Apply rules (UDP)
          when: rules_command.changed
          shell: IFACE={{public_if}} /etc/network/if-pre-up.d/shathel-fwopener-{{ opener_stack_name }}-iptables


        - name: Shathel rules file (TCP)
          template:
            src: ./shathel.iptable.tcp.rules.j2
            dest: /etc/iptables/shathel.fwopener.tcp.{{ opener_stack_name }}.rules
            owner: root
            mode: 0644
          register: rules_command
          when: "opener_tcp_ports != ''"
        - name: Adding shathel iptables rules applied on startup (TCP)
          template:
            src: ./shathel.iptable.tcp.apply.j2
            dest: /etc/network/if-pre-up.d/shathel-fwopener-tcp-{{ opener_stack_name }}-iptables
            owner: root
            mode: 0755
          when: "opener_tcp_ports != ''"
        - name: Apply rules (TCP)
          when: rules_command.changed
          shell: IFACE={{public_if}} /etc/network/if-pre-up.d/shathel-fwopener-tcp-{{ opener_stack_name }}-iptables
