---
- hosts: all
  become: yes
  tasks:
        - name: Get public interface name
          shell: ip addr show | grep {{public_ip}} | cut -f2 | awk '{ print $7 }' | head
          register: if_name_command
          changed_when: False
        - name: Get private name if public not avail (scaleway???)
          shell: ip addr show | grep {{private_ip}} | cut -f2 | awk '{ print $7 }' | head
          register: if_name_command
          when: "if_name_command.rc != 0 or if_name_command.stdout == ''"
          changed_when: False
        - name: Save if name
          set_fact:
            public_if: "{{ if_name_command.stdout }}"
          failed_when: "if_name_command.rc != 0 or if_name_command.stdout == ''"
        - name: /etc/iptables dir present
          file:
            path: /etc/iptables
            state: directory
        - name: Shathel rules file
          template:
              src: ./shathel.iptable.rules.j2
              dest: /etc/iptables/shathel.fwopener.{{ opener_stack_name }}.rules
              owner: root
              mode: 0644
          register: rules_command
        - name: Adding shathel iptables rules applied on startup
          template:
              src: ./shathel.iptable.apply.j2
              dest: /etc/network/if-pre-up.d/shathel-fwopener-{{ opener_stack_name }}-iptables
              owner: root
              mode: 0755
        - name: Apply rules
          when: rules_command.changed
          shell: IFACE={{public_if}} /etc/network/if-pre-up.d/shathel-fwopener-{{ opener_stack_name }}-iptables
