version: '3'
services:
  gitlab-runner:
    image: flakm/gitlab-runner-auto-register:0.0.6
    deploy:
      mode: global
    environment:
      - CI_SERVER_URL=${SHATHEL_ENV_GITLAB_URL}
      - REGISTRATION_TOKEN=${SHATHEL_ENV_GITLAB_TOKEN}
      - ADMIN_TOKEN=${SHATHEL_ENV_GITLAB_ADMIN_TOKEN}
      - PROJECTS_TO_REGISTER=${SHATHEL_ENV_GITLAB_PROJECTS_TO_REGISTER}
      - CUSTOM_RUNNER_NAME=${SHATHEL_ENV_GITLAB_CUSTOM_RUNNER_NAME}
      - LOCKED_MODE=${SHATHEL_ENV_GITLAB_LOCKED_MODE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock