version: '3'
services:
  gitlab-runner:
    image: flakm/gitlab-runner-auto-register:0.0.9
    deploy:
      mode: global
        resources:
          limits:
            memory:  ${SHATHEL_ENV_RUNNER_MEMORY_LIMIT:-2gb}
    hostname: "{{.Node.Hostname}}-${SHATHEL_ENV_GITLAB_CUSTOM_RUNNER_NAME:-runner}"
    environment:
      - CI_SERVER_URL=${SHATHEL_ENV_GITLAB_URL}
      - REGISTRATION_TOKEN=${SHATHEL_ENV_GITLAB_TOKEN}
      - ADMIN_TOKEN=${SHATHEL_ENV_GITLAB_ADMIN_TOKEN}
      - PROJECTS_TO_REGISTER=${SHATHEL_ENV_GITLAB_PROJECTS_TO_REGISTER}
      - REGISTER_LOCKED=${SHATHEL_ENV_GITLAB_LOCKED_MODE}
      - DOCKER_PRIVILEGED=${SHATHEL_ENV_GITLAB_PRIVILEGED_MODE}
      - DOCKER_VOLUMES=/var/run/docker.sock:/var/run/docker.sock.host
      - RUNNER_TAG_LIST=${SHATHEL_ENV_GITLAB_TAGS}
      - REGISTER_RUN_UNTAGGED=${SHATHEL_ENV_GITLAB_REGISTER_RUN_UNTAGGED}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
