version: '3'
services:
  gitlab-runner:
    image: flakm/gitlab-runner-auto-register:0.0.2
    container_name: gitlab-runner
    environment:
      - CI_SERVER_URL=${SHATHEL_ENV_GITLAB_URL}
      - REGISTRATION_TOKEN=${SHATHEL_ENV_GITLAB_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock