version: "3.1"
services:
  proxy:
    image: dockerflow/docker-flow-proxy:18.07.06-72
    ports:
      - 8080:8080
      - ${SHATHEL_PROXY_PORT_HTTP:-80}:80
      - ${SHATHEL_PROXY_PORT_HTTPS:-443}:443
    networks:
      - network
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=http-keep-alive
    deploy:
      update_config:
        delay: 15s
      replicas: 1
      resources:
          limits:
            memory:  ${SHATHEL_ENV_PROXY_MEMORY_LIMIT:-128mb}
    secrets:
      - source: shathel_dfp_users_monitoring
        target: dfp_users_monitoring
      - source: shathel_dfp_xip_io_pem
        target: cert_xip_io.pem

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.06.03-26
    ports:
      - 9999:8080
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
          limits:
            memory:  ${SHATHEL_ENV_SWARM_LISTENER_MEMORY_LIMIT:-16mb}
secrets:
  shathel_dfp_users_monitoring:
    file: ./data/default-proxy-users
  shathel_dfp_xip_io_pem:
    file: ./data/certs/xip.io.pem
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.44.0/24