version: "3.1"
services:
  proxy:
    image: vfarcic/docker-flow-proxy:1.299
    ports:
      - 8080:8080
      - ${SHATHEL_PROXY_PORT_HTTP:-80}:80
      - ${SHATHEL_PROXY_PORT_HTTPS:-443}:443
    networks:
      - network
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=http-keep-alive
    deploy:
      update_config:
        delay: 15s
      replicas: 2
    secrets:
      - source: shathel_dfp_users_monitoring
        target: dfp_users_monitoring
      - source: shathel_dfp_xip_io_pem
        target: xip_io.pem

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:1.32
    ports:
      - 9999:8080
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
secrets:
  shathel_dfp_users_monitoring:
    file: ./data/default-proxy-users
  shathel_dfp_xip_io_pem:
    file: ./data/certs/xip.io.pem
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.44.0/24